apiVersion: apps/v1
kind: Deployment
metadata:
  name: autograder-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autograder-web
  template:
    metadata:
      labels:
        app: autograder-web
    spec:
      containers:
        - name: autograder-gke-web
          image: gcr.io/formidable-gate-337712/autograder-web:latest
          ports:
            - containerPort: 8080
          env:
            - name: ENV
              value: prod
            - name: PORT
              value: "8080"
            - name: GRPC_PORT
              value: "6000"
            - name: ENDPOINT
              value: "cal/cs170/sp22"
            - name: CLOUDFLARE_ZONE
              value: "ef77efc0233a87a84ceecfdebbbc9415"
            - name: LEADERBOARD_URL
              value: "https://project.cs170.dev/scoreboard/"
          envFrom:
            - secretRef:
                name: web-secrets
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5

        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.28.0
          command:
            - "/cloud_sql_proxy"
            - "-instances=formidable-gate-337712:us-west2:cs170-db=tcp:5432"
            - "-enable_iam_login"
            - "-ip_address_types=PRIVATE"
          securityContext:
            runAsNonRoot: true
      serviceAccountName: autograder-web
