apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: scaled-judge
spec:
  jobTargetRef:
    parallelism: 1
    completions: 1
    activeDeadlineSeconds: 60
    backoffLimit: 0
    template:
      metadata:
        labels:
          app: scaled-judge-worker
      spec:
        runtimeClassName: gvisor
        initContainers:
          - name: judge-subscriber
            image: gcr.io/formidable-gate-337712/autograder-judge:latest
            volumeMounts:
              - name: workdir
                mountPath: /workdir
            env:
              - name: MODE
                value: SUBSCRIBE
            envFrom:
              - secretRef:
                  name: judge-secrets
          - name: judge-executor
            image: gcr.io/formidable-gate-337712/autograder-judge:latest
            volumeMounts:
              - name: workdir
                mountPath: /workdir
            env:
              - name: MODE
                value: JUDGE
            resources:
              limits:
                cpu: 500m
                memory: 1G
              requests:
                cpu: 500m
                memory: 1G
        containers:
          - name: judge-publisher
            image: gcr.io/formidable-gate-337712/autograder-judge:latest
            volumeMounts:
              - name: workdir
                mountPath: /workdir
            env:
              - name: MODE
                value: PUBLISH
            envFrom:
              - secretRef:
                  name: judge-secrets
        restartPolicy: Never
        volumes:
          - name: workdir
            emptyDir: {}
          - name: secrets
            secret:
              secretName: judge-secrets
  pollingInterval: 5
  maxReplicaCount: 10
  rolloutStrategy: gradual
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  triggers:
    - type: external
      metadata:
        scalerAddress: "judge-scaler.default.svc.cluster.local:6001"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: judge-worker-policy
spec:
  podSelector:
    matchLabels:
      app: scaled-judge-worker
  policyTypes:
    - Ingress
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: judge-scaler
      ports:
        - protocol: TCP
          port: 6000
    - to:
      - namespaceSelector:
          matchLabels:
            name: kube-system
      ports:
      - port: 53
        protocol: UDP
