apiVersion: v1
kind: Service
metadata:
  name: judge-scaler
spec:
  ports:
  - port: 6000
    targetPort: 6000
  selector:
    app: judge-scaler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge-scaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge-scaler
  template:
    metadata:
      labels:
        app: judge-scaler
    spec:
      containers:
      - name: scaler
        image: gcr.io/formidable-gate-337712/autograder-judge-scaler:latest
        env:
          - name: ENV
            value: prod
        ports:
        - containerPort: 6000
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.28.0
        command:
          - "/cloud_sql_proxy"
          - "-instances=formidable-gate-337712:us-west2:cs170-db=tcp:5432"
          - "-enable_iam_login"
          - "-ip_address_types=PRIVATE"
        securityContext:
          runAsNonRoot: true
      serviceAccountName: autograder-web
---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: scaled-judge
spec:
  jobTargetRef:
    parallelism: 1
    completions: 1
    activeDeadlineSeconds: 60
    backoffLimit: 0
    template:
      spec:
        runtimeClassName: gvisor
        initContainers:
          - name: judge-subscriber
            image: gcr.io/formidable-gate-337712/autograder-judge:latest
            volumeMounts:
              - name: workdir
                mountPath: /workdir
              - name: secrets
                mountPath: /secrets
            env:
              - name: MODE
                value: SUBSCRIBE
          - name: judge-executor
            image: gcr.io/formidable-gate-337712/autograder-judge:latest
            volumeMounts:
              - name: workdir
                mountPath: /workdir
            env:
              - name: MODE
                value: JUDGE
        containers:
          - name: judge-publisher
            image: gcr.io/formidable-gate-337712/autograder-judge:latest
            volumeMounts:
              - name: workdir
                mountPath: /workdir
              - name: secrets
                mountPath: /secrets
            env:
              - name: MODE
                value: PUBLISH
              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: /secrets/credentials.json
        restartPolicy: Never
        volumes:
          - name: workdir
            emptyDir: {}
          - name: secrets
            secret:
              secretName: judge-secrets
  pollingInterval: 5
  maxReplicaCount: 10
  rolloutStrategy: gradual
  successfulJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 5
  triggers:
    - type: external
      metadata:
        scalerAddress: "judge-scaler.default.svc.cluster.local:6000"
