apiVersion: v1
kind: Service
metadata:
  name: web-frontend
spec:
  selector:
    app: autograder-web
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: grpc
      port: 6000
      targetPort: 6000
